# Generated by Django 6.0.4 on 2026-05-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        ('user', '0002_remove_user_company_alter_company_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyleave',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='applyleave',
            name='role',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='role',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='role',
        ),
        migrations.AddField(
            model_name='applyleave',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
