# Generated by Django 6.0.4 on 2026-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_applyleave_empid_remove_applyleave_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='compensation_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='paid_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.IntegerField(default=0),
        ),
    ]
