# Generated by Django 6.0.4 on 2026-05-22 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_user_company_alter_company_owner_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('PAN Card', 'PAN Card'), ('Resume', 'Resume'), ('Offer Letter', 'Offer Letter'), ('Joining Letter', 'Joining Letter'), ('Experience Certificate', 'Experience Certificate'), ('Educational Certificate', 'Educational Certificate'), ('Salary Slip', 'Salary Slip'), ('ID Proof', 'ID Proof'), ('Other', 'Other')], max_length=100)),
                ('document_file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
