# Generated by Django 6.0.4 on 2026-05-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comp_code', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('telegram_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
