# Generated by Django 6.0.4 on 2026-05-09 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
        ('user', '0002_remove_user_company_alter_company_owner_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramdetails',
            name='user_id',
        ),
        migrations.AddField(
            model_name='telegramdetails',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='telegramdetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='telegramdetails',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='telegramdetails',
            table='telebot_telegramdetails',
        ),
    ]
