# Generated by Django 6.0.4 on 2026-05-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0002_remove_telegramdetails_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramdetails',
            name='empid',
            field=models.CharField(max_length=20),
        ),
    ]
