# Generated by Django 6.0.4 on 2026-05-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='duration_leaves',
        ),
    ]
