# Generated by Django 6.0.4 on 2026-05-08 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_remove_salary_duration_leaves'),
        ('user', '0002_remove_user_company_alter_company_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='empid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
