# Generated by Django 6.0.4 on 2026-05-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='empid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.company'),
            preserve_default=False,
        ),
    ]
